language: python

python:
  - "2.7"
  - "3.3"
  - "pypy"

install:
  - pip install -r dev-requirements.txt
  - pip install . --quiet
  - pip install coveralls

script: coverage run --source=flask_jwt setup.py test

after_success:
  - coveralls

branches:
  only:
    - master
